# [Numpy Operations](https://numpy.org/doc/stable/reference/routines.array-manipulation.html#)

***

### Math operations

In [31]:
import numpy as np
A = np.ones((4,4))*-4
print('A:\n', A)
print('A+A:\n', A+A)
print('A-A:\n', A-A)
print('A*A:\n', A*A) 
print('A/A:\n', A/A)
print('0.5*A:\n', 0.5*A)
print('absolute value:\n', np.absolute(A))
print('square root:\n', np.sqrt(np.absolute(A)))
print('ln:\n', np.log(np.absolute(A)))
print('log10:\n', np.log10(np.absolute(A)))

A:
 [[-4. -4. -4. -4.]
 [-4. -4. -4. -4.]
 [-4. -4. -4. -4.]
 [-4. -4. -4. -4.]]
A+A:
 [[-8. -8. -8. -8.]
 [-8. -8. -8. -8.]
 [-8. -8. -8. -8.]
 [-8. -8. -8. -8.]]
A-A:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
A*A:
 [[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
A/A:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
0.5*A:
 [[-2. -2. -2. -2.]
 [-2. -2. -2. -2.]
 [-2. -2. -2. -2.]
 [-2. -2. -2. -2.]]
absolute value:
 [[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
square root:
 [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
ln:
 [[1.38629436 1.38629436 1.38629436 1.38629436]
 [1.38629436 1.38629436 1.38629436 1.38629436]
 [1.38629436 1.38629436 1.38629436 1.38629436]
 [1.38629436 1.38629436 1.38629436 1.38629436]]
log10:
 [[0.60205999 0.60205999 0.60205999 0.60205999]
 [0.60205999 0.60205999 0.60205999 0.60205999]
 [0.60205999 0.60205999 0.60205999 0.60205999]
 [0.60205999 0.60205999 0.60205999 0.6

In [36]:
# mean(), std(), sum(), max()
data = np.array([[1,1,1],[2,2,2],[3,3,3]])
print('Max: ', data.max())
print('Mean: ', data.mean())
print('Sum: ', data.sum())
print('Std: ', data.std())

Max:  3
Mean:  2.0
Sum:  18
Std:  0.816496580927726


*** 
### Matrix operations

In [40]:
# transpose
data = [[1,2,3],[3,5,7],[2,6,8]]
a =np.array(data)
print(a)
a.transpose() # or np.transpose(a)

[[1 2 3]
 [3 5 7]
 [2 6 8]]


array([[1, 3, 2],
       [2, 5, 6],
       [3, 7, 8]])

In [41]:
# dot product
data1 = np.array([[1,1,1],[2,2,2]]) 
data2 = np.array([[0,0,0],[1,1,1]]) 
print(data1)
print(data2)
dot_product = np.dot(data1, data2.transpose())
dot_product

[[1 1 1]
 [2 2 2]]
[[0 0 0]
 [1 1 1]]


array([[0, 3],
       [0, 6]])