# [Numpy Array](https://numpy.org/doc/stable/reference/routines.array-creation.html)
* [Array constuction](#1)
* 

<a id = 1></a>
***
### Array Construction  

In [1]:
# 1D array
import numpy as np
data = [1,2,3,5]
np_array = np.array(data)
print(np_array)
# get values
np_array[2]

[1 2 3 5]


3

In [2]:
# 2D array (ndarray)
data = [[1,2,3],[3,5,7],[2,6,8]]
np_ndarray = np.array(data)
print(np_ndarray)
# get values 
print('index [1][0]: ', np_ndarray[1][0])
print('index [0:1]: ', np_ndarray[0:2])

[[1 2 3]
 [3 5 7]
 [2 6 8]]
index [1][0]:  3
index [0:1]:  [[1 2 3]
 [3 5 7]]
