# [Numpy Array](https://numpy.org/doc/stable/reference/routines.array-creation.html)

<a id = 1></a>
***
### Array construction  

In [1]:
# 1D array
import numpy as np
data = [1,2,3,5]
np_array = np.array(data)
print(np_array)
# get values
np_array[2]

[1 2 3 5]


3

In [4]:
# 2D array (ndarray)
data = [[1,2,3],[3,5,7],[2,6,8],[7,8,9]]
np_ndarray = np.array(data)
print(np_ndarray)
# get values 
print('index [1][0]: ', np_ndarray[1][0])
print('index [0:1]: ', np_ndarray[0:2])

[[1 2 3]
 [3 5 7]
 [2 6 8]
 [7 8 9]]
index [1][0]:  3
index [0:1]:  [[1 2 3]
 [3 5 7]]


In [17]:
# eye, zeros, ones
print('eye:\n',np.eye(3))
print('ones:\n', np.ones((2,3)))
print('zeros:\n', np.zeros((2,3)))

eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
# random 
print(np.random.random((2,3)))

[[0.40620508 0.71889066 0.84637163]
 [0.81460958 0.4583199  0.54378808]]


*** 
### Reshape array

In [6]:
# show shape => return (row#, column#) 
np_ndarray.shape

(4, 3)

In [9]:
# reshape((new row#, new column#))
a = np.arange(6)
print(a)
print(a.reshape((3, 2)))

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
