# [Numpy Operations](https://numpy.org/doc/stable/reference/routines.array-manipulation.html#)


*** 
### Transpose

In [2]:
import numpy as np
# transpose
data = [[1,2,3],[3,5,7],[2,6,8]]
a =np.array(data)
print(a)
a.transpose() # or np.transpose(a)

[[1 2 3]
 [3 5 7]
 [2 6 8]]


array([[1, 3, 2],
       [2, 5, 6],
       [3, 7, 8]])